import{esc,formatTimelineDate}from'./render.js';
const labels={milk:'奶量',water:'喝水',stool:'便便',urine:'尿尿'};
export function recordsView({records=[],sleeps=[],observations=[],reminders=[],dataError=''}={}) {
  const rows=records.slice().sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt)).map(item=>`<article class="meal-row"><div><b>${labels[item.type]||esc(item.type)} · ${esc(item.value)}${['stool','urine'].includes(item.type)?' 次':''}</b><small>${esc(formatTimelineDate(item.occurredAt))}</small></div><div class="button-row"><button data-action="edit-record" data-id="${esc(item.id)}">编辑</button><button data-action="delete-record" data-id="${esc(item.id)}">删除</button></div></article>`).join('');
  const sleepRows=sleeps.filter(item=>item.endAt).sort((a,b)=>b.startAt.localeCompare(a.startAt)).map(item=>`<article class="meal-row"><div><b>${esc(item.type==='night'?'夜间睡眠':item.type==='nap'?'午间小睡':'睡眠记录')} · ${esc(item.durationMinutes)} 分钟</b><small>${esc(formatTimelineDate(item.startAt))}</small></div><div class="button-row"><button data-action="edit-sleep" data-id="${esc(item.id)}">编辑</button><button data-action="delete-sleep" data-id="${esc(item.id)}">删除</button></div></article>`).join('');
  const foodRows=observations.map(item=>`<article class="meal-row"><div><b>新食物 · ${esc(item.name)}</b><small>观察至 ${esc(item.observeUntil)} · 已记 ${item.reactions?.length||0} 天</small></div><div class="button-row"><button data-action="add-reaction" data-id="${esc(item.id)}">记录反应</button><button data-action="delete-observation" data-id="${esc(item.id)}">删除</button></div></article>`).join('');
  const reminderRows=reminders.map(item=>`<article class="meal-row"><div><b>${esc(item.title)}</b><small>${esc(item.dueDate)} · ${item.completedAt?'已完成':'待提醒'}</small></div><div class="button-row">${item.completedAt?'':`<button data-action="complete-reminder" data-id="${esc(item.id)}">完成</button>`}<button data-action="delete-reminder" data-id="${esc(item.id)}">删除</button></div></article>`).join('');
  const active=sleeps.find(item=>!item.endAt),history=rows+sleepRows+foodRows+reminderRows,errorStatus=dataError?`<p class="empty" role="status">${esc(dataError)}</p>`:'';
  const activeMinutes=active?Math.max(0,Math.floor((Date.now()-new Date(active.startAt).getTime())/60000)):0,sleepStatus=active?(activeMinutes?`已睡 ${activeMinutes} 分钟`:'正在睡眠'):'尚未开始';
  const sleepAction=active?`<button class="sleep-main-action" data-action="sleep-end" data-id="${esc(active.id)}">结束睡眠</button>`:'<button class="sleep-main-action" data-action="sleep-start">开始睡眠</button>';
  return`<div class="page-stack"><section class="page-title"><p class="eyebrow">日常记录</p><h2>记录每一个小变化</h2></section><div class="feature-grid"><button class="feature-card" data-record="milk"><span>🍼</span><b>奶量</b><small>记录时间和毫升数</small></button><button class="feature-card" data-record="water"><span>💧</span><b>喝水</b><small>查看今日累计</small></button><button class="feature-card" data-record="stool" aria-label="记录便便"><span>🌿</span><b>记录便便</b><small>一键记为 1 次</small></button><button class="feature-card" data-record="urine" aria-label="记录尿尿"><span>💧</span><b>记录尿尿</b><small>一键记为 1 次</small></button><button class="feature-card" data-record="new-food"><span>🥕</span><b>新食材</b><small>连续三天观察</small></button><button class="feature-card" data-record="reminder"><span>🔔</span><b>提醒</b><small>疫苗、体检、自定义</small></button></div><section class="panel"><div class="section-heading"><h2>睡眠计时</h2><span>${sleepStatus}</span></div><div class="sleep-controls">${sleepAction}<button class="sleep-secondary-action text-button" data-record="sleep">补记睡眠</button></div></section><section id="record-editor" class="panel"><h2>最近记录与提醒</h2>${errorStatus}${history||'<p class="muted">还没有记录。</p>'}</section></div>`;
}
