import{IndexedDbRepository}from'./db.js';
import{AppStore}from'./store.js';
import{createRouter}from'./router.js';
import{createId}from'./core/id.js';
import{localDateKey}from'./core/dates.js';
import{STORE_NAMES}from'./core/schema.js';
import{createDefaultTemplate}from'./features/schedule/template.js';
import{generateTasks,completeTask,skipTask,adjustTask,updateOverdue}from'./features/schedule/engine.js';
import{selectPrimaryTask}from'./features/schedule/select-current.js';
import{generateWeek,replaceMeal,setMealStatus}from'./features/meals/planner.js';
import{saveCurrentWeek,weekStart}from'./features/meals/week-menu.js';
import{createMenuBrowser,historyMenus,runMenuMutation,resetMenuBrowserForBoundary}from'./features/meals/menu-browser.js';
import{persistRecipePreference}from'./features/meals/preferences.js';
import{buildShoppingList}from'./features/meals/shopping.js';
import{createNumericRecord,persistCountRecord,updateDailyRecord}from'./features/records/records.js';
import{createSleepSession,sleepDurationMinutes,minutesOverlappingLocalDay}from'./features/records/sleep.js';
import{applySleepAnchor,restoreSleepAnchors}from'./features/schedule/sleep-anchor.js';
import{createObservation}from'./features/records/new-food.js';
import{buildTimeline}from'./features/growth/timeline.js';
import{chartModel}from'./features/growth/chart.js';
import{dailyTrendModel}from'./features/growth/daily-trends.js';
import{createBackup,previewBackup,importBackup,restoreBackupIntoEmpty,resetApplication}from'./features/backup/backup.js';
import{auditAndMarkV2}from'./features/migration/v2.js';
import{notificationState,requestNotifications,notifyDueTasks,nextNotificationDelay}from'./features/notifications/notifications.js';
import{recipes}from'../data/recipes.js';
import{mount,esc}from'./ui/render.js';
import{todayView}from'./ui/today.js';
import{mealsView}from'./ui/meals.js';
import{recordsView}from'./ui/records.js';
import{growthView,chartSvg}from'./ui/growth.js';
import{settingsView}from'./ui/settings.js';
import{onboardingView}from'./ui/onboarding.js';
import{toast}from'./ui/feedback.js';
import{openDialog,openActionDialog}from'./ui/dialogs.js';

const menuGenerationFlights=new Map();
export function generateCurrentMenu({repository,weeks,current,baby,recipes:catalog,date=localDateKey(),confirm=globalThis.confirm,generate=generateWeek,save=saveCurrentWeek,createId:idFactory=createId}){const key=baby.id;if(menuGenerationFlights.has(key))return menuGenerationFlights.get(key);if(current&&!confirm('本周菜单已存在，继续将覆盖本周菜单，是否继续？'))return Promise.resolve(null);const flight=(async()=>{const generated=generate(catalog,{babyId:baby.id,stage:baby.stage,startDate:weekStart(date),createId:idFactory});await save(repository,weeks,generated);return generated})().finally(()=>menuGenerationFlights.delete(key));menuGenerationFlights.set(key,flight);return flight}
export function confirmHistoryEdit(browser,ask=globalThis.confirm){if(!ask('正在修改过去的饮食记录，是否继续？'))return false;browser.editHistory();return true}
export async function runMenuGeneration({button,notify=toast,refresh,showCurrent,generation}){if(button.disabled)return null;button.disabled=true;try{const generated=await generateCurrentMenu(generation);if(!generated)return null;showCurrent();await refresh();return generated}catch(error){notify(error.message);return null}finally{button.disabled=false}}

export async function loadApplicationModel(repository,options){const store=await new AppStore(repository,options).load();if(!store.babies.length)return{store,needsOnboarding:true};await auditAndMarkV2(repository);await store.load();return{store,needsOnboarding:false}}
export async function loadRenderData(repository,{seed={}}={}){const recoverable=new Set(['dailyRecords','sleepSessions']),entries=await Promise.all(STORE_NAMES.map(async store=>{if(Array.isArray(seed[store]))return[store,seed[store],null];try{return[store,await repository.list(store),null]}catch(error){return[store,[],error instanceof Error?error:new Error(String(error))]}})),data={},errors={};for(const[store,items,error]of entries){if(error&&!recoverable.has(store))throw error;data[store]=items;if(error)errors[store]=error}return{data,errors}}
export function createRefreshCoordinator(){let generation=0;return{begin:()=>++generation,invalidate:()=>++generation,isCurrent:token=>token===generation}}
export function createAsyncEpoch(){let generation=0,suspended=false;return{capture(){const token=generation;return()=>token===generation&&!suspended},invalidate(){generation++;suspended=true},resume(){suspended=false}}}
export function syncNotifiedTasks(target,settings){target.clear();for(const id of settings?.notifiedTaskIds||[])if(typeof id==='string'&&id)target.add(id);return target}
export class ReplacementCommittedError extends Error{constructor(cause){super('数据已导入，请重新打开应用');this.name='ReplacementCommittedError';this.committed=true;this.cause=cause}}
export function lockApplicationAfterCommittedReplacement(document,reload=()=>globalThis.location?.reload()){document.body.innerHTML='<main class="fatal" role="alert" aria-live="assertive"><h1>数据已导入，请重新打开应用</h1><p>为避免旧页面继续修改新数据，应用已停止当前操作。</p><button id="replacement-reload" type="button">重新加载应用</button></main>';document.getElementById('replacement-reload').onclick=reload}
export async function runDataReplacement({epoch,invalidateRefresh=()=>{},clearTimer=()=>{},replace,sync,refresh,schedule}){invalidateRefresh();epoch.invalidate();clearTimer();let replaced=false;try{await replace();replaced=true;await sync();await refresh();epoch.resume();await schedule()}catch(error){if(!replaced){epoch.resume();await schedule();throw error}throw new ReplacementCommittedError(error)}}
export async function changeNotificationScheduling({enabled,epoch,clearTimer=()=>{},persist,schedule}){epoch.invalidate();clearTimer();try{await persist(enabled)}catch(error){epoch.resume();await schedule();throw error}if(enabled){epoch.resume();await schedule()}}
export async function runNotificationSchedule({repository,snapshot=null,settings:providedSettings,babyId,tasks=[],notifiedTasks,registration,isCurrent=()=>true,now=new Date().toISOString()}){let settings=providedSettings||snapshot?.data.appSettings.find(item=>item.id==='global');if(!settings){settings=await repository.get('appSettings','global');if(!isCurrent())return null}let reminderSource=snapshot?.data.reminders;if(!reminderSource){reminderSource=await repository.list('reminders',{babyId});if(!isCurrent())return null}const reminders=reminderSource.filter(item=>item.babyId===babyId&&!item.completedAt).map(item=>({id:`reminder-${item.id}`,title:item.title,plannedAt:new Date(`${item.dueDate}T09:00:00`).toISOString(),status:'upcoming'})),items=[...tasks,...reminders],pending=items.filter(task=>!notifiedTasks.has(task.id)),messages=await notifyDueTasks(pending,{registration,isCurrent,now});if(!isCurrent())return null;for(const message of messages)notifiedTasks.add(message.taskId);if(notifiedTasks.size){if(!isCurrent())return null;await repository.put('appSettings',{...settings,notifiedTaskIds:[...notifiedTasks],updatedAt:new Date().toISOString()});if(!isCurrent())return null}return nextNotificationDelay(items.filter(task=>!notifiedTasks.has(task.id)),now)}
function commitStore(target,source){for(const key of['babies','settings','activeBabyId','tasks','allTasks','week','weeks','timeline'])target[key]=source[key]}
export async function runRefreshCycle({store,repository,render,schedule,coordinator=createRefreshCoordinator()}){const token=coordinator.begin(),localStore=new AppStore(repository,{now:store.now});try{await localStore.load();if(!coordinator.isCurrent(token))return null;const loaded=await loadRenderData(repository,{seed:{babies:localStore.babies,appSettings:localStore.settings?[localStore.settings]:[],taskInstances:localStore.allTasks,weeklyMenus:localStore.weeks}});if(!coordinator.isCurrent(token))return null;const babyId=localStore.activeBabyId,snapshot={...loaded,babyId,isCurrent:()=>coordinator.isCurrent(token)&&store.activeBabyId===babyId};commitStore(store,localStore);if(!snapshot.isCurrent())return null;await render(snapshot);if(!snapshot.isCurrent())return null;await schedule(snapshot,snapshot.isCurrent);if(!snapshot.isCurrent())return null;return snapshot}catch(error){if(!coordinator.isCurrent(token))return null;throw error}}
export async function loadDailyTrend(repository,{babyId,metric='sleep',days=7,endDate,now=new Date(),records:loadedRecords,sleeps:loadedSleeps}={}){if(!babyId)return null;let records=loadedRecords,sleeps=loadedSleeps;if(!Array.isArray(records)||!Array.isArray(sleeps))[records,sleeps]=await Promise.all([repository.list('dailyRecords',{babyId}),repository.list('sleepSessions',{babyId})]);records=records.filter(item=>item.babyId===babyId);sleeps=sleeps.filter(item=>item.babyId===babyId);return dailyTrendModel({records,sleeps,metric,days,endDate,now})}
export function createTrendState(){let state={metric:'sleep',days:7};return{value:()=>({...state}),setMetric(metric){if(!['sleep','milk','stool','urine'].includes(metric))throw new Error('趋势指标无效');state={...state,metric};return this.value()},setDays(days){const value=Number(days);if(![7,14,30].includes(value))throw new Error('趋势范围无效');state={...state,days:value};return this.value()},reset(){state={metric:'sleep',days:7};return this.value()}}}
export function bindOnboardingActions(document,{repository,saveOnboarding,onRestored,beforeRestore=()=>{},afterRestore=()=>{},onRestoreFailed=()=>{},notify=toast,restore=restoreBackupIntoEmpty,loadModel=loadApplicationModel,readForm=form=>Object.fromEntries(new FormData(form))}){
 const form=document.getElementById('onboarding-form'),input=document.getElementById('onboarding-backup');let locked=false;
 form.onsubmit=async event=>{event.preventDefault();if(locked)return;await saveOnboarding(readForm(event.currentTarget))};
 input.onchange=async event=>{const file=event.target.files[0];if(!file)return;let restored=false;try{const text=await file.text();beforeRestore();const result=await restore(repository,text);restored=true;const model=await loadModel(repository);await onRestored(model);await afterRestore();document.querySelector('.modal-backdrop')?.remove();notify(`已恢复 ${result.babyCount} 个宝宝、${result.recordCount} 条记录`)}catch(error){if(restored){locked=true;const modal=document.querySelector('.modal-backdrop'),message='数据已恢复，请重新打开应用',status=document.getElementById('onboarding-recovery-status');modal?.querySelectorAll('input,select,button').forEach(control=>{control.disabled=true});modal?.querySelector('label[for="onboarding-backup"]')?.setAttribute('aria-disabled','true');status.textContent=message;status.hidden=false;notify(message)}else{await onRestoreFailed();notify(error.message)}}finally{event.target.value=''}};
}
export function bindRecipeSearchInput(input,{apply,delay=150,setTimer=setTimeout,clearTimer=clearTimeout}={}){let composing=false,timer=null;const schedule=()=>{if(timer!==null)clearTimer(timer);timer=setTimer(()=>{timer=null;if(input.isConnected)apply()},delay)};input.addEventListener('compositionstart',()=>{composing=true;if(timer!==null){clearTimer(timer);timer=null}});input.addEventListener('compositionend',()=>{composing=false;schedule()});input.addEventListener('input',event=>{if(composing||event.isComposing)return;schedule()});return()=>{if(timer!==null)clearTimer(timer)}}
export async function ensureDailySchedule(repository,baby,now=new Date(),idFactory=createId){const date=localDateKey(now),existing=(await repository.list('taskInstances',{babyId:baby.id})).filter(task=>task.date===date);if(existing.length)return existing;let template=(await repository.list('scheduleTemplates',{babyId:baby.id}))[0];if(!template){template=createDefaultTemplate(baby.id);await repository.put('scheduleTemplates',template)}const wakeAt=new Date(`${date}T08:00:00`).toISOString(),tasks=generateTasks({babyId:baby.id,date,wakeAt,template,createId:idFactory});for(const task of tasks)await repository.put('taskInstances',task);return tasks}
export function formatDateTimeLocal(value){const date=value instanceof Date?value:new Date(value),pad=part=>String(part).padStart(2,'0');if(Number.isNaN(date.getTime()))return'';return`${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`}
export async function recalculateScheduleForSleep(repository,session){if(!session?.babyId||!session.endAt||!['night','nap'].includes(session.type)||Number.isNaN(new Date(session.endAt).getTime()))throw new Error('睡眠记录无法用于作息重算');const date=localDateKey(new Date(session.endAt)),tasks=(await repository.list('taskInstances',{babyId:session.babyId})).filter(task=>task.date===date),template=(await repository.list('scheduleTemplates',{babyId:session.babyId}))[0],updated=applySleepAnchor(tasks,{...session,date},{napToMealMinutes:template?.napToMealMinutes??120});for(const task of updated)await repository.put('taskInstances',task);return updated}
export async function replaySleepScheduleAtomically(repository,{nextSession=null,previousSession=null,deleteId=null}={}){const babyId=nextSession?.babyId||previousSession?.babyId;if(!babyId)throw new Error('睡眠记录缺少宝宝');if(nextSession&&nextSession.babyId!==babyId)throw new Error('睡眠记录宝宝不一致');const dates=new Set([previousSession?.endAt,nextSession?.endAt].filter(Boolean).map(value=>localDateKey(new Date(value))));return repository.transaction(['sleepSessions','taskInstances','scheduleTemplates'],async tx=>{if(deleteId)await tx.delete('sleepSessions',deleteId);else if(nextSession)await tx.put('sleepSessions',nextSession);const sessions=(await tx.list('sleepSessions',{babyId})).filter(item=>item.endAt&&['night','nap'].includes(item.type)),template=(await tx.list('scheduleTemplates',{babyId}))[0],configured=Number(template?.napToMealMinutes),napToMealMinutes=Number.isFinite(configured)&&configured>=0?configured:120;for(const date of dates){let tasks=restoreSleepAnchors((await tx.list('taskInstances',{babyId})).filter(task=>task.date===date));const replay=sessions.filter(item=>localDateKey(new Date(item.endAt))===date).sort((a,b)=>new Date(a.endAt)-new Date(b.endAt));for(const session of replay)tasks=applySleepAnchor(tasks,{...session,date},{napToMealMinutes});for(const task of tasks)await tx.put('taskInstances',task)}return nextSession})}

async function browserApp(){
 const repo=new IndexedDbRepository(),model=await loadApplicationModel(repo);let store=model.store;
 let trendState=createTrendState();
 let menuBrowser=createMenuBrowser();
 let recipeBrowser={stage:null,query:'',chewingLevel:'all',fingerFood:'all',limit:24};
 let notificationRegistration=null,notificationTimer=null;const initialSettings=await repo.get('appSettings','global')||{},notifiedTasks=new Set(initialSettings.notifiedTaskIds||[]);
 const refreshCoordinator=createRefreshCoordinator(),scheduleEpoch=createAsyncEpoch();
 function beginDataReplacement(){refreshCoordinator.invalidate();scheduleEpoch.invalidate();clearTimeout(notificationTimer)}
 function wireUpdatePrompt(registration){let reloading=false;const offer=worker=>{if(worker&&confirm('发现新版本，是否现在更新？当前本地记录不会丢失。'))worker.postMessage({type:'SKIP_WAITING'})};if(registration.waiting)offer(registration.waiting);registration.addEventListener('updatefound',()=>{const worker=registration.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)offer(worker)})});navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!reloading){reloading=true;location.reload()}})}
 const router=createRouter({onRoute:render});router.bind();let mainStarted=false;
  async function startMainApp(nextModel={store}){store=nextModel.store;trendState.reset();resetMenuBrowserForBoundary(menuBrowser);syncNotifiedTasks(notifiedTasks,store.settings);if(mainStarted)return refresh({schedule:false});mainStarted=true;if(store.activeBaby){await ensureDailySchedule(repo,store.activeBaby);await store.load()}await render();if('serviceWorker'in navigator){notificationRegistration=await navigator.serviceWorker.register('./service-worker.js');wireUpdatePrompt(notificationRegistration);await scheduleNotifications()}document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refresh()});window.addEventListener('focus',()=>scheduleNotifications())}
 async function scheduleNotifications(snapshot=null,refreshGuard=()=>true){clearTimeout(notificationTimer);const epochGuard=scheduleEpoch.capture(),isCurrent=()=>epochGuard()&&refreshGuard();if(!isCurrent()||notificationState()!=='granted'||!notificationRegistration)return;const settings=snapshot?.data.appSettings.find(item=>item.id==='global')||await repo.get('appSettings','global');if(!isCurrent()||settings?.notificationsEnabled===false)return;const delay=await runNotificationSchedule({repository:repo,snapshot,settings,babyId:store.activeBabyId,tasks:store.tasks,notifiedTasks,registration:notificationRegistration,isCurrent});if(delay!==null&&isCurrent()){const timerGuard=scheduleEpoch.capture();notificationTimer=setTimeout(()=>scheduleNotifications(null,timerGuard),Math.min(delay+250,2147483647))}}
 async function refresh({schedule=true}={}){return runRefreshCycle({store,repository:repo,coordinator:refreshCoordinator,render:snapshot=>render(router.current,snapshot),schedule:schedule?scheduleNotifications:async()=>{}})}
 async function saveSleepAndRecalculate(session,previousSession=null){await replaySleepScheduleAtomically(repo,{nextSession:session,previousSession});await refresh()}
 async function render(route='today',snapshot=null){
  if(!store.activeBaby)return;
  const{data:allData,errors:dataErrors}=snapshot||await loadRenderData(repo,{seed:{babies:store.babies,appSettings:store.settings?[store.settings]:[],taskInstances:store.allTasks,weeklyMenus:store.weeks}}),line=buildTimeline(allData,{babyId:store.activeBabyId}),tasks=updateOverdue(store.tasks,new Date().toISOString()),primary=selectPrimaryTask(tasks),primaryIndex=tasks.findIndex(x=>x.id===primary?.id),next=tasks.slice(primaryIndex+1).find(x=>!['completed','skipped'].includes(x.status));
   const sleeps=allData.sleepSessions.filter(item=>item.babyId===store.activeBabyId),today=localDateKey(),sleepMinutes=sleeps.reduce((sum,item)=>sum+minutesOverlappingLocalDay(item,today),0),recordDataError=dataErrors.dailyRecords||dataErrors.sleepSessions;let trend=null,trendError='';if(recordDataError)trendError='趋势数据暂时无法读取，请稍后重试';else try{trend=await loadDailyTrend(repo,{babyId:store.activeBabyId,...trendState.value(),endDate:today,now:new Date(),records:allData.dailyRecords,sleeps})}catch(error){console.error('趋势数据读取失败',error);trendError='趋势数据暂时无法读取，请稍后重试'}
   if(snapshot?.isCurrent&&!snapshot.isCurrent())return;
   const preferences=allData.foodPreferences.find(item=>item.id===store.activeBabyId||item.babyId===store.activeBabyId)||{id:store.activeBabyId,babyId:store.activeBabyId,excluded:[],disliked:[],favorites:[]},shopping=allData.shoppingItems.filter(item=>item.babyId===store.activeBabyId);
  mount('view-today',todayView({baby:store.activeBaby,primary,next,sleepMinutes,sleepUnavailable:Boolean(dataErrors.sleepSessions),timeline:line}));
  if(!recipeBrowser.stage)recipeBrowser.stage=store.activeBaby.stage;
  menuBrowser.reconcile(store.weeks);mount('view-meals',mealsView({week:store.week,weeks:store.weeks,menuBrowser:menuBrowser.value(),recipes,stage:store.activeBaby.stage,shopping,preferences,recipeBrowser}));
   mount('view-records',recordsView({records:allData.dailyRecords.filter(x=>x.babyId===store.activeBabyId),sleeps,observations:allData.newFoodObservations.filter(x=>x.babyId===store.activeBabyId),reminders:allData.reminders.filter(x=>x.babyId===store.activeBabyId),dataError:recordDataError?'记录数据暂时无法读取，请稍后重试':''}));mount('view-growth',growthView({timeline:line,chart:chartModel(allData.growthMeasurements.filter(x=>x.babyId===store.activeBabyId),'weight'),trend,trendError}));mount('view-settings',settingsView({baby:store.activeBaby,babies:store.babies}));
  document.getElementById('baby-greeting').textContent=`${store.activeBaby.name}的今天`;
  document.getElementById('today-date').textContent=new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'});
  bindActions();
 }
 async function saveOnboarding(values){const now=new Date().toISOString(),baby={id:createId(),name:values.name.trim(),birthday:values.birthday||'',stage:values.stage,createdAt:now,updatedAt:now};await repo.put('babies',baby);await repo.put('appSettings',{id:'global',activeBabyId:baby.id,createdAt:now,updatedAt:now});const template=createDefaultTemplate(baby.id);await repo.put('scheduleTemplates',template);const wakeAt=new Date(`${localDateKey()}T${values.wake||'08:00'}:00`).toISOString();const tasks=generateTasks({babyId:baby.id,date:localDateKey(),wakeAt,template,createId});for(const task of tasks)await repo.put('taskInstances',task);document.querySelector('.modal-backdrop')?.remove();await store.load();await startMainApp({store});toast('已创建宝宝的第一天');}
 function bindActions(){
  async function handleCompleteKeep(id){const now=new Date().toISOString();for(const task of completeTask(store.tasks,id,now,{cascade:false}))await repo.put('taskInstances',task);await refresh();toast('已完成，后续时间保持不变')}
  async function handleAdjustTask(id){const task=store.tasks.find(item=>item.id===id),values=await openDialog({title:'调整当前事项',body:`<label>计划时间</label><input name="time" type="time" value="${new Date(task.plannedAt).toTimeString().slice(0,5)}" required>`});if(!values)return;await repo.put('taskInstances',adjustTask(task,new Date(`${task.date}T${values.time}:00`).toISOString(),new Date().toISOString()));await refresh();toast('事项时间已调整')}
  async function handleSkipTask(id){for(const task of skipTask(store.tasks,id))await repo.put('taskInstances',task);await refresh();toast('已跳过当前事项')}
  document.querySelectorAll('[data-action="complete-task"]').forEach(button=>button.onclick=async()=>{const now=new Date().toISOString();for(const task of completeTask(store.tasks,button.dataset.id,now,{cascade:true}))await repo.put('taskInstances',task);await refresh();toast('已完成，下一事项已更新')});
  document.querySelectorAll('[data-action="task-more"]').forEach(button=>button.onclick=async()=>{const action=await openActionDialog({title:'更多操作'});switch(action){case'keep':return handleCompleteKeep(button.dataset.id);case'adjust':return handleAdjustTask(button.dataset.id);case'skip':return handleSkipTask(button.dataset.id)}});
  document.querySelector('[data-action="menu-current"]')?.addEventListener('click',async()=>{menuBrowser.showCurrent();await render(router.current)});document.querySelector('[data-action="menu-history"]')?.addEventListener('click',async()=>{menuBrowser.showHistory(historyMenus(store.weeks,{babyId:store.activeBabyId,date:localDateKey()})[0]?.id||null);await render(router.current)});document.querySelectorAll('[data-action="select-history"]').forEach(button=>button.onclick=async()=>{menuBrowser.selectHistory(button.dataset.id);await render(router.current)});document.querySelector('[data-action="edit-history"]')?.addEventListener('click',async()=>{if(!confirmHistoryEdit(menuBrowser))return;await render(router.current)});
  document.querySelector('[data-action="generate-menu"]')?.addEventListener('click',async event=>{const prefs=await repo.get('foodPreferences',store.activeBabyId)||{},generated=await runMenuGeneration({button:event.currentTarget,refresh,showCurrent:()=>menuBrowser.showCurrent(),generation:{repository:repo,weeks:store.weeks,current:store.week,baby:store.activeBaby,recipes,generate:(catalog,options)=>generateWeek(catalog,{...options,excluded:prefs.excluded||[],favorites:prefs.favorites||[],disliked:prefs.disliked||[]})}});if(generated)toast('本周菜单已生成')});
  const menuControls=menuId=>[...document.querySelectorAll('[data-menu-id]')].filter(control=>control.dataset.menuId===menuId);
  document.querySelectorAll('[data-action="replace-meal"]').forEach(button=>button.onclick=async()=>{const updated=await runMenuMutation({repository:repo,menuId:button.dataset.menuId,babyId:store.activeBabyId,controls:menuControls(button.dataset.menuId),prepare:async()=>await repo.get('foodPreferences',store.activeBabyId)||{},mutate:(menu,prefs)=>replaceMeal(menu,button.dataset.id,recipes,{stage:store.activeBaby.stage,excluded:prefs.excluded||[],favorites:prefs.favorites||[],disliked:prefs.disliked||[]}),refresh,notify:toast});if(updated)toast('已更换为安全候选食谱')});
  document.querySelectorAll('[data-action="meal-status"]').forEach(button=>button.onclick=async()=>{const updated=await runMenuMutation({repository:repo,menuId:button.dataset.menuId,babyId:store.activeBabyId,controls:menuControls(button.dataset.menuId),mutate:menu=>setMealStatus(menu,button.dataset.id,button.dataset.status),refresh,notify:toast});if(updated)toast('餐次状态已更新')});
  document.querySelector('[data-action="build-shopping"]')?.addEventListener('click',async()=>{if(!store.week)return toast('请先生成菜单');for(const item of await repo.list('shoppingItems',{babyId:store.activeBabyId}))if(!item.custom)await repo.delete('shoppingItems',item.id);for(const item of buildShoppingList(store.week,recipes,createId))await repo.put('shoppingItems',item);await refresh();toast('买菜清单已生成')});
  document.querySelectorAll('[data-action="toggle-shopping"]').forEach(input=>input.onchange=async()=>{const item=await repo.get('shoppingItems',input.dataset.id);await repo.put('shoppingItems',{...item,done:input.checked,inStock:input.checked?false:item.inStock,updatedAt:new Date().toISOString()});await refresh()});
  document.querySelectorAll('[data-action="stock-shopping"]').forEach(button=>button.onclick=async()=>{const item=await repo.get('shoppingItems',button.dataset.id);await repo.put('shoppingItems',{...item,inStock:!item.inStock,done:false,updatedAt:new Date().toISOString()});await refresh()});
  document.querySelector('[data-action="add-shopping"]')?.addEventListener('click',async()=>{const values=await openDialog({title:'添加买菜项目',body:'<label>名称</label><input name="name" required><label>数量</label><input name="quantity" type="number" min="1" value="1">'});if(values){const now=new Date().toISOString();await repo.put('shoppingItems',{id:createId(),babyId:store.activeBabyId,name:values.name.trim(),quantity:Number(values.quantity)||1,done:false,inStock:false,custom:true,createdAt:now,updatedAt:now});await refresh()}});
  document.querySelectorAll('[data-action="favorite-recipe"]').forEach(button=>button.onclick=async()=>{await persistRecipePreference(repo,store.activeBabyId,button.dataset.id,recipes,'favorite');await refresh()});
  document.querySelectorAll('[data-action="dislike-food"]').forEach(button=>button.onclick=async()=>{await persistRecipePreference(repo,store.activeBabyId,button.dataset.id,recipes,'dislike');await refresh()});
  const readRecipeFilters=()=>({stage:document.getElementById('recipe-stage')?.value||store.activeBaby.stage,query:document.getElementById('recipe-search')?.value||'',chewingLevel:document.getElementById('recipe-chewing-level')?.value||'all',fingerFood:document.getElementById('recipe-finger-food')?.value||'all',limit:24});
  const applyRecipeFilters=async focusSearch=>{recipeBrowser=readRecipeFilters();await render(router.current);if(focusSearch){const input=document.getElementById('recipe-search');input?.focus();input?.setSelectionRange(input.value.length,input.value.length)}};
  const recipeSearch=document.getElementById('recipe-search');if(recipeSearch)bindRecipeSearchInput(recipeSearch,{apply:()=>applyRecipeFilters(true)});for(const id of['recipe-stage','recipe-chewing-level','recipe-finger-food'])document.getElementById(id)?.addEventListener('change',()=>applyRecipeFilters(false));
  document.querySelector('[data-action="load-more-recipes"]')?.addEventListener('click',async()=>{recipeBrowser={...recipeBrowser,limit:recipeBrowser.limit+24};await render(router.current)});
  document.querySelectorAll('[data-quick],[data-record]').forEach(button=>button.onclick=async()=>{if(button.disabled)return;button.disabled=true;try{const type=button.dataset.quick||button.dataset.record;if(['stool','urine'].includes(type)){await persistCountRecord(repo,{babyId:store.activeBabyId,type},createId);await refresh();toast(type==='stool'?'便便已记录':'尿尿已记录')}else await openRecord(type)}catch(error){toast(`记录失败：${error.message||error}`)}finally{button.disabled=false}});
  document.querySelector('[data-action="sleep-start"]')?.addEventListener('click',async()=>{const values=await openDialog({title:'开始睡眠',body:'<label>睡眠类型</label><select name="type"><option value="nap">午间小睡</option><option value="night">夜间睡眠</option></select><label>备注（可选）</label><textarea name="note"></textarea>'});if(!values)return;await repo.put('sleepSessions',createSleepSession({babyId:store.activeBabyId,type:values.type,startAt:new Date().toISOString(),note:values.note},createId));await refresh();toast('睡眠计时已开始')});
  document.querySelector('[data-action="sleep-end"]')?.addEventListener('click',async event=>{const item=await repo.get('sleepSessions',event.currentTarget.dataset.id),endAt=new Date().toISOString();await saveSleepAndRecalculate({...item,endAt,durationMinutes:sleepDurationMinutes(item.startAt,endAt),updatedAt:endAt});toast('睡眠记录已完成')});
  document.querySelectorAll('[data-action="edit-record"]').forEach(button=>button.onclick=async()=>{const item=await repo.get('dailyRecords',button.dataset.id),countType=['stool','urine'].includes(item.type),label=item.type==='stool'?'便便':item.type==='urine'?'尿尿':'记录',body=countType?`<label>次数</label><input name="value" type="number" min="1" step="1" value="${esc(item.value)}" required><label>发生时间</label><input name="occurredAt" type="datetime-local" value="${formatDateTimeLocal(item.occurredAt)}" required><label>备注</label><textarea name="note">${esc(item.note||'')}</textarea>`:`<label>数值</label><input name="value" type="number" min="0" value="${esc(item.value)}" required><label>备注</label><textarea name="note">${esc(item.note||'')}</textarea>`;await openDialog({title:`编辑${label}`,body,onSubmit:async values=>{await updateDailyRecord(repo,{id:item.id,value:values.value,note:values.note,occurredAt:countType?values.occurredAt:undefined});await refresh();toast('记录已更新')}})});
  document.querySelectorAll('[data-action="delete-record"]').forEach(button=>button.onclick=async()=>{if(!confirm('删除这条记录？'))return;await repo.delete('dailyRecords',button.dataset.id);await refresh();toast('记录已删除')});
  document.querySelectorAll('[data-action="edit-sleep"]').forEach(button=>button.onclick=async()=>{const item=await repo.get('sleepSessions',button.dataset.id),values=await openDialog({title:'编辑睡眠',body:`<label>睡眠类型</label><select name="type"><option value="nap" ${item.type==='nap'?'selected':''}>午间小睡</option><option value="night" ${item.type==='night'?'selected':''}>夜间睡眠</option></select><label>开始时间</label><input name="startAt" type="datetime-local" value="${formatDateTimeLocal(item.startAt)}" required><label>结束时间</label><input name="endAt" type="datetime-local" value="${formatDateTimeLocal(item.endAt)}" required><label>备注</label><textarea name="note">${esc(item.note||'')}</textarea>`});if(!values)return;try{const updated=createSleepSession({babyId:item.babyId,type:values.type,startAt:new Date(values.startAt).toISOString(),endAt:new Date(values.endAt).toISOString(),note:values.note},()=>item.id);await saveSleepAndRecalculate({...updated,createdAt:item.createdAt,updatedAt:new Date().toISOString()},item);toast('睡眠记录已更新')}catch(error){toast(error.message)}});
  document.querySelectorAll('[data-action="delete-sleep"]').forEach(button=>button.onclick=async()=>{if(!confirm('删除这条睡眠记录？'))return;const item=await repo.get('sleepSessions',button.dataset.id);await replaySleepScheduleAtomically(repo,{previousSession:item,deleteId:item.id});await refresh();toast('睡眠记录已删除')});
  document.querySelectorAll('[data-action="add-reaction"]').forEach(button=>button.onclick=async()=>{const item=await repo.get('newFoodObservations',button.dataset.id),values=await openDialog({title:`记录 ${esc(item.name)} 的反应`,body:`<label>日期</label><input name="date" type="date" value="${localDateKey()}" required><label>反应</label><textarea name="reaction" required></textarea>`});if(!values)return;await repo.put('newFoodObservations',{...item,reactions:[...(item.reactions||[]),{date:values.date,text:values.reaction.trim()}],updatedAt:new Date().toISOString()});await refresh();toast('观察反应已保存')});
  document.querySelectorAll('[data-action="delete-observation"]').forEach(button=>button.onclick=async()=>{if(!confirm('删除这项新食物观察？'))return;await repo.delete('newFoodObservations',button.dataset.id);await refresh()});
  document.querySelectorAll('[data-action="complete-reminder"]').forEach(button=>button.onclick=async()=>{const item=await repo.get('reminders',button.dataset.id),now=new Date().toISOString();await repo.put('reminders',{...item,completedAt:now,updatedAt:now});await refresh();toast('提醒已完成')});
  document.querySelectorAll('[data-action="delete-reminder"]').forEach(button=>button.onclick=async()=>{if(!confirm('删除这条提醒？'))return;await repo.delete('reminders',button.dataset.id);await refresh()});
  document.querySelectorAll('[data-growth]').forEach(button=>button.onclick=()=>openGrowth(button.dataset.growth));
  document.getElementById('chart-type')?.addEventListener('change',async event=>{const records=await repo.list('growthMeasurements',{babyId:store.activeBabyId});document.getElementById('growth-chart').innerHTML=chartSvg(chartModel(records,event.target.value))});
  document.getElementById('timeline-filter')?.addEventListener('change',event=>{document.querySelectorAll('#view-growth .timeline article').forEach(item=>item.hidden=event.target.value!=='all'&&item.dataset.type!==event.target.value)});
  document.querySelectorAll('[data-trend-metric]').forEach(button=>button.onclick=async()=>{trendState.setMetric(button.dataset.trendMetric);await render(router.current)});
  document.querySelectorAll('[data-trend-days]').forEach(button=>button.onclick=async()=>{trendState.setDays(button.dataset.trendDays);await render(router.current)});
  document.getElementById('active-baby')?.addEventListener('change',async event=>{await store.setActiveBaby(event.target.value);trendState.reset();resetMenuBrowserForBoundary(menuBrowser);await ensureDailySchedule(repo,store.activeBaby);await refresh()});
  document.querySelector('[data-action="add-baby"]')?.addEventListener('click',()=>openBaby());
  document.querySelector('[data-action="edit-profile"]')?.addEventListener('click',()=>openProfile());
  document.querySelector('[data-action="delete-baby"]')?.addEventListener('click',deleteBaby);
  document.querySelector('[data-action="edit-schedule"]')?.addEventListener('click',()=>openSchedule());
  document.querySelector('[data-action="food-preferences"]')?.addEventListener('click',()=>openPreferences());
  document.querySelector('[data-action="notification-settings"]')?.addEventListener('click',enableNotifications);
  document.querySelector('[data-action="export-data"]')?.addEventListener('click',exportData);
  document.getElementById('backup-file')?.addEventListener('change',importData);
  document.querySelector('[data-action="reset-data"]')?.addEventListener('click',resetData);
 }
 async function openRecord(type){if(type==='new-food'){const values=await openDialog({title:'记录新食材',body:`<label>食材名称</label><input name="name" required><label>首次尝试日期</label><input name="date" type="date" value="${localDateKey()}" required><label>观察备注</label><textarea name="note"></textarea>`});if(values){const item=createObservation({babyId:store.activeBabyId,name:values.name,date:values.date},createId);await repo.put('newFoodObservations',{...item,note:values.note});await refresh();toast('已开始三天观察')}return}if(type==='reminder'){const values=await openDialog({title:'添加提醒',body:`<label>类型</label><select name="type"><option value="vaccine">疫苗</option><option value="checkup">体检</option><option value="custom">自定义</option></select><label>标题</label><input name="title" required><label>日期</label><input name="dueDate" type="date" value="${localDateKey()}" required>`});if(values){const now=new Date().toISOString();await repo.put('reminders',{id:createId(),babyId:store.activeBabyId,...values,completedAt:null,createdAt:now,updatedAt:now});await refresh();toast('提醒已保存')}return}if(type==='sleep'){const now=new Date(),values=await openDialog({title:'补记睡眠',body:`<label>睡眠类型</label><select name="type"><option value="nap">午间小睡</option><option value="night">夜间睡眠</option></select><label>开始时间</label><input name="startAt" type="datetime-local" value="${formatDateTimeLocal(new Date(now.getTime()-60*60000))}" required><label>结束时间</label><input name="endAt" type="datetime-local" value="${formatDateTimeLocal(now)}" required><label>备注</label><textarea name="note"></textarea>`});if(!values)return;try{const session=createSleepSession({babyId:store.activeBabyId,type:values.type,startAt:new Date(values.startAt).toISOString(),endAt:new Date(values.endAt).toISOString(),note:values.note},createId);await saveSleepAndRecalculate(session);toast('记录已保存')}catch(error){toast(error.message)}return}const label=type==='milk'?'奶量':type==='water'?'喝水':'排便次数',values=await openDialog({title:`记录${label}`,body:`<label for="record-value">${label}</label><input id="record-value" name="value" type="number" min="0" required><label for="record-note">备注</label><textarea id="record-note" name="note"></textarea>`});if(!values)return;await repo.put('dailyRecords',createNumericRecord({babyId:store.activeBabyId,type,value:values.value,note:values.note,occurredAt:new Date().toISOString()},createId));await refresh();toast('记录已保存')}
 async function openGrowth(field){if(field==='tooth'){const values=await openDialog({title:'记录长牙',body:`<label>第几颗牙</label><input name="number" type="number" min="1" required><label>日期</label><input name="date" type="date" value="${localDateKey()}" required><label>备注</label><textarea name="note"></textarea>`});if(values){const now=new Date().toISOString();await repo.put('toothRecords',{id:createId(),babyId:store.activeBabyId,number:Number(values.number),date:values.date,note:values.note.trim(),createdAt:now,updatedAt:now});await refresh();toast('长牙记录已保存')}return}const step=field==='weight'?'0.01':'0.1',values=await openDialog({title:`记录${field==='weight'?'体重':'身高'}`,body:`<label for="growth-value">数值</label><input id="growth-value" name="value" type="number" step="${step}" min="0" required><label for="growth-date">日期</label><input id="growth-date" name="date" type="date" value="${localDateKey()}" required>`});if(!values)return;const now=new Date().toISOString();await repo.put('growthMeasurements',{id:createId(),babyId:store.activeBabyId,date:values.date,[field]:Number(values.value),createdAt:now,updatedAt:now});await refresh();toast('成长记录已保存')}
 async function openBaby(){const values=await openDialog({title:'添加宝宝',body:'<label>昵称</label><input name="name" required><label>出生日期</label><input name="birthday" type="date"><label>辅食阶段</label><select name="stage"><option value="stage1">初尝泥糊期</option><option value="stage2">稠泥碎末期</option><option value="stage3">软烂颗粒期</option><option value="stage4">咀嚼练习期</option><option value="stage5">家庭餐过渡期</option></select>'});if(values)await saveOnboarding(values)}
 async function openProfile(){const baby=store.activeBaby,values=await openDialog({title:'编辑宝宝资料',body:`<label>昵称</label><input name="name" value="${esc(baby.name)}" required><label>生日</label><input name="birthday" type="date" value="${esc(baby.birthday||'')}"><label>辅食阶段</label><select name="stage"><option value="${esc(baby.stage)}">保持当前阶段</option><option value="stage1">初尝泥糊期</option><option value="stage2">稠泥碎末期</option><option value="stage3">软烂颗粒期</option><option value="stage4">咀嚼练习期</option><option value="stage5">家庭餐过渡期</option></select>`});if(values){await repo.put('babies',{...baby,...values,updatedAt:new Date().toISOString()});await refresh()}}
 async function deleteBaby(){if(store.babies.length<=1)return toast('至少保留一个宝宝');if(!confirm(`删除“${store.activeBaby.name}”及其全部本地数据？`))return;const id=store.activeBabyId;for(const name of STORE_NAMES){for(const item of await repo.list(name,{babyId:id}))await repo.delete(name,item.id)}await repo.delete('babies',id);const next=store.babies.find(b=>b.id!==id);await repo.put('appSettings',{id:'global',activeBabyId:next.id,updatedAt:new Date().toISOString()});trendState.reset();resetMenuBrowserForBoundary(menuBrowser);await refresh();toast('宝宝及其本地数据已删除')}
 async function openSchedule(){const template=(await repo.list('scheduleTemplates',{babyId:store.activeBabyId}))[0]||createDefaultTemplate(store.activeBabyId),fields=template.rules.map((rule,index)=>`<fieldset><label><input name="enabled-${index}" type="checkbox" ${index===0||rule.enabled!==false?'checked':''} ${index===0?'disabled':''}>启用</label><label>事项名称</label><input name="title-${index}" value="${esc(rule.title)}" required><label>距上一事项（分钟）</label><input name="after-${index}" type="number" min="0" value="${rule.afterMinutes}" required></fieldset>`).join(''),values=await openDialog({title:'配置每日作息',body:`${fields}<label>午睡结束后多久吃辅食（分钟）</label><input name="napToMealMinutes" type="number" min="0" value="${template.napToMealMinutes??120}" required><fieldset><legend>添加自定义事项（可选）</legend><label>名称</label><input name="customTitle"><label>类型</label><select name="customType"><option value="meal">辅食</option><option value="milk">喝奶</option><option value="sleep">睡眠</option><option value="custom">其他</option></select><label>距上一事项（分钟）</label><input name="customAfter" type="number" min="0" value="60"></fieldset>`});if(values){template.rules=template.rules.map((rule,index)=>({...rule,title:values[`title-${index}`].trim(),afterMinutes:Number(values[`after-${index}`]),enabled:index===0||values[`enabled-${index}`]==='on'})).filter(rule=>rule.enabled!==false);template.napToMealMinutes=Number(values.napToMealMinutes);if(values.customTitle?.trim())template.rules.push({type:values.customType,title:values.customTitle.trim(),afterMinutes:Number(values.customAfter)});template.updatedAt=new Date().toISOString();await repo.put('scheduleTemplates',template);toast('作息模板已保存，明日任务将使用新安排')}}
 async function openPreferences(){const prefs=await repo.get('foodPreferences',store.activeBabyId)||{id:store.activeBabyId,babyId:store.activeBabyId,excluded:[],disliked:[],favorites:[]},values=await openDialog({title:'饮食偏好',body:`<label>绝对排除（逗号分隔）</label><input name="excluded" value="${esc((prefs.excluded||[]).join(','))}"><label>不喜欢（逗号分隔）</label><input name="disliked" value="${esc((prefs.disliked||[]).join(','))}">`});if(values){const split=value=>value.split(/[,，]/).map(x=>x.trim()).filter(Boolean),now=new Date().toISOString();await repo.put('foodPreferences',{...prefs,excluded:split(values.excluded),disliked:split(values.disliked),createdAt:prefs.createdAt||now,updatedAt:now});await refresh();toast('饮食规则已保存')}}
 async function enableNotifications(){if(notificationState()==='unsupported')return toast('当前浏览器不支持通知');const settings=await repo.get('appSettings','global')||{id:'global'},persist=enabled=>repo.put('appSettings',{...settings,notificationsEnabled:enabled,updatedAt:new Date().toISOString()});if(settings.notificationsEnabled!==false&&notificationState()==='granted'){await changeNotificationScheduling({enabled:false,epoch:scheduleEpoch,clearTimer:()=>clearTimeout(notificationTimer),persist,schedule:scheduleNotifications});return toast('应用内提醒已关闭')}if(!confirm('通知只能尽力提醒，不能作为医疗或安全报警。是否继续开启？'))return;const permission=await requestNotifications();if(permission==='granted')await changeNotificationScheduling({enabled:true,epoch:scheduleEpoch,clearTimer:()=>clearTimeout(notificationTimer),persist,schedule:scheduleNotifications});toast(permission==='granted'?'通知已开启，再次点击可关闭':'未获得通知权限')}
 async function exportData(){const backup=await createBackup(repo),blob=new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`宝宝成长助手V1备份-${localDateKey()}.json`;link.click();URL.revokeObjectURL(link.href);localStorage.setItem('babyGrowthAssistantV1LastExport',backup.exportedAt);toast('备份已导出')}
 async function importData(event){const file=event.target.files[0];if(!file)return;try{const text=await file.text(),preview=previewBackup(text);if(confirm(`备份包含 ${preview.babyCount} 个宝宝、${preview.recordCount} 条数据。确认覆盖当前数据？`)){await runDataReplacement({epoch:scheduleEpoch,invalidateRefresh:()=>refreshCoordinator.invalidate(),clearTimer:()=>clearTimeout(notificationTimer),replace:()=>importBackup(repo,text),sync:async()=>syncNotifiedTasks(notifiedTasks,await repo.get('appSettings','global')),refresh:async()=>{trendState.reset();resetMenuBrowserForBoundary(menuBrowser);await refresh({schedule:false})},schedule:scheduleNotifications});toast('备份导入成功')}}catch(error){if(error.committed){beginDataReplacement();lockApplicationAfterCommittedReplacement(document)}else toast(error.message)}finally{event.target.value=''}}
 async function resetData(){if(!confirm('确定清除这台设备上的全部 V1 数据吗？此操作不可恢复。'))return;if(!confirm('请再次确认：是否已导出备份并继续清除？'))return;await resetApplication(repo);location.reload()}
 if(model.needsOnboarding){document.body.insertAdjacentHTML('beforeend',onboardingView());bindOnboardingActions(document,{repository:repo,saveOnboarding,onRestored:startMainApp,beforeRestore:beginDataReplacement,afterRestore:async()=>{scheduleEpoch.resume();await scheduleNotifications()},onRestoreFailed:async()=>{scheduleEpoch.resume();await scheduleNotifications()}})}else await startMainApp(model);
}

if(typeof document!=='undefined')browserApp().catch(error=>{console.error(error);document.body.innerHTML=`<main class="fatal"><h1>应用启动失败</h1><p>${String(error.message||error)}</p><button onclick="location.reload()">重新加载</button></main>`});
