import{IndexedDbRepository}from'./db.js';
import{AppStore}from'./store.js';
import{createRouter}from'./router.js';
import{createId}from'./core/id.js';
import{localDateKey}from'./core/dates.js';
import{STORE_NAMES}from'./core/schema.js';
import{createDefaultTemplate}from'./features/schedule/template.js';
import{generateTasks,completeTask,skipTask,updateOverdue}from'./features/schedule/engine.js';
import{selectPrimaryTask}from'./features/schedule/select-current.js';
import{generateWeek,replaceMeal,setMealStatus}from'./features/meals/planner.js';
import{buildShoppingList}from'./features/meals/shopping.js';
import{createNumericRecord}from'./features/records/records.js';
import{createSleepSession,minutesOverlappingLocalDay}from'./features/records/sleep.js';
import{createObservation}from'./features/records/new-food.js';
import{buildTimeline}from'./features/growth/timeline.js';
import{chartModel}from'./features/growth/chart.js';
import{createBackup,previewBackup,importBackup,resetApplication}from'./features/backup/backup.js';
import{notificationState,requestNotifications,notifyDueTasks,nextNotificationDelay}from'./features/notifications/notifications.js';
import{recipes}from'../data/recipes.js';
import{mount,esc}from'./ui/render.js';
import{todayView}from'./ui/today.js';
import{mealsView}from'./ui/meals.js';
import{recordsView}from'./ui/records.js';
import{growthView,chartSvg}from'./ui/growth.js';
import{settingsView}from'./ui/settings.js';
import{onboardingView}from'./ui/onboarding.js';
import{toast}from'./ui/feedback.js';
import{openDialog}from'./ui/dialogs.js';

export async function loadApplicationModel(repository,options){const store=await new AppStore(repository,options).load();return{store,needsOnboarding:!store.babies.length}}
export async function ensureDailySchedule(repository,baby,now=new Date(),idFactory=createId){const date=localDateKey(now),existing=(await repository.list('taskInstances',{babyId:baby.id})).filter(task=>task.date===date);if(existing.length)return existing;let template=(await repository.list('scheduleTemplates',{babyId:baby.id}))[0];if(!template){template=createDefaultTemplate(baby.id);await repository.put('scheduleTemplates',template)}const wakeAt=new Date(`${date}T08:00:00`).toISOString(),tasks=generateTasks({babyId:baby.id,date,wakeAt,template,createId:idFactory});for(const task of tasks)await repository.put('taskInstances',task);return tasks}

async function browserApp(){
 const repo=new IndexedDbRepository(),model=await loadApplicationModel(repo),store=model.store;
 let notificationRegistration=null,notificationTimer=null;const initialSettings=await repo.get('appSettings','global')||{},notifiedTasks=new Set(initialSettings.notifiedTaskIds||[]);
 function wireUpdatePrompt(registration){let reloading=false;const offer=worker=>{if(worker&&confirm('发现新版本，是否现在更新？当前本地记录不会丢失。'))worker.postMessage({type:'SKIP_WAITING'})};if(registration.waiting)offer(registration.waiting);registration.addEventListener('updatefound',()=>{const worker=registration.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)offer(worker)})});navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!reloading){reloading=true;location.reload()}})}
 if(store.activeBaby){await ensureDailySchedule(repo,store.activeBaby);await store.load()}
 const router=createRouter({onRoute:render});router.bind();
 async function scheduleNotifications(){clearTimeout(notificationTimer);const settings=await repo.get('appSettings','global');if(settings?.notificationsEnabled===false||notificationState()!=='granted'||!notificationRegistration)return;const reminders=(await repo.list('reminders',{babyId:store.activeBabyId})).filter(item=>!item.completedAt).map(item=>({id:`reminder-${item.id}`,title:item.title,plannedAt:new Date(`${item.dueDate}T09:00:00`).toISOString(),status:'upcoming'})),items=[...store.tasks,...reminders],pending=items.filter(task=>!notifiedTasks.has(task.id));for(const message of await notifyDueTasks(pending,{registration:notificationRegistration}))notifiedTasks.add(message.taskId);if(notifiedTasks.size)await repo.put('appSettings',{...settings,notifiedTaskIds:[...notifiedTasks],updatedAt:new Date().toISOString()});const delay=nextNotificationDelay(items.filter(task=>!notifiedTasks.has(task.id)));if(delay!==null)notificationTimer=setTimeout(scheduleNotifications,Math.min(delay+250,2147483647))}
 async function refresh(){await store.load();await render(router.current);await scheduleNotifications()}
 async function render(route='today'){
  if(!store.activeBaby)return;
  const allData=await repo.exportAll(),line=buildTimeline(allData,{babyId:store.activeBabyId}),tasks=updateOverdue(store.tasks,new Date().toISOString()),primary=selectPrimaryTask(tasks),primaryIndex=tasks.findIndex(x=>x.id===primary?.id),next=tasks.slice(primaryIndex+1).find(x=>!['completed','skipped'].includes(x.status));
  const sleeps=await repo.list('sleepSessions',{babyId:store.activeBabyId}),today=localDateKey(),sleepMinutes=sleeps.reduce((sum,item)=>sum+minutesOverlappingLocalDay(item,today),0);
  const preferences=await repo.get('foodPreferences',store.activeBabyId)||{id:store.activeBabyId,babyId:store.activeBabyId,excluded:[],disliked:[],favorites:[]},shopping=await repo.list('shoppingItems',{babyId:store.activeBabyId});
  mount('view-today',todayView({baby:store.activeBaby,primary,next,sleepMinutes,timeline:line}));
  mount('view-meals',mealsView({week:store.week,recipes,stage:store.activeBaby.stage,shopping,preferences}));
  mount('view-records',recordsView({records:allData.dailyRecords.filter(x=>x.babyId===store.activeBabyId),sleeps,observations:allData.newFoodObservations.filter(x=>x.babyId===store.activeBabyId),reminders:allData.reminders.filter(x=>x.babyId===store.activeBabyId)}));mount('view-growth',growthView({timeline:line,chart:chartModel(allData.growthMeasurements.filter(x=>x.babyId===store.activeBabyId),'weight')}));mount('view-settings',settingsView({baby:store.activeBaby,babies:store.babies}));
  document.getElementById('baby-greeting').textContent=`${store.activeBaby.name}的今天`;
  document.getElementById('today-date').textContent=new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'});
  bindActions();
 }
 async function saveOnboarding(values){const now=new Date().toISOString(),baby={id:createId(),name:values.name.trim(),birthday:values.birthday||'',stage:values.stage,createdAt:now,updatedAt:now};await repo.put('babies',baby);await repo.put('appSettings',{id:'global',activeBabyId:baby.id,createdAt:now,updatedAt:now});const template=createDefaultTemplate(baby.id);await repo.put('scheduleTemplates',template);const wakeAt=new Date(`${localDateKey()}T${values.wake||'08:00'}:00`).toISOString();const tasks=generateTasks({babyId:baby.id,date:localDateKey(),wakeAt,template,createId});for(const task of tasks)await repo.put('taskInstances',task);document.querySelector('.modal-backdrop')?.remove();await refresh();toast('已创建宝宝的第一天');}
 function bindActions(){
  document.querySelectorAll('[data-action="complete-task"]').forEach(button=>button.onclick=async()=>{const nextTask=store.tasks.slice(store.tasks.findIndex(task=>task.id===button.dataset.id)+1).find(task=>!['completed','skipped'].includes(task.status)),values=await openDialog({title:'完成并顺延',body:`<label>下一事项时间（可选）</label><input name="nextTime" type="time" value="${nextTask?new Date(nextTask.plannedAt).toTimeString().slice(0,5):''}"><p class="muted">留空会按作息间隔自动顺延。</p>`});if(!values)return;const now=new Date(),nextPlannedAt=values.nextTime?new Date(`${localDateKey(now)}T${values.nextTime}:00`).toISOString():undefined,tasks=completeTask(store.tasks,button.dataset.id,now.toISOString(),{cascade:true,nextPlannedAt});for(const task of tasks)await repo.put('taskInstances',task);await refresh();toast('已完成，下一事项已更新')});
  document.querySelectorAll('[data-action="complete-task-keep"]').forEach(button=>button.onclick=async()=>{const now=new Date().toISOString();for(const task of completeTask(store.tasks,button.dataset.id,now,{cascade:false}))await repo.put('taskInstances',task);await refresh();toast('已完成，后续时间保持不变')});
  document.querySelectorAll('[data-action="adjust-task"]').forEach(button=>button.onclick=async()=>{const task=store.tasks.find(item=>item.id===button.dataset.id),values=await openDialog({title:'调整当前事项',body:`<label>计划时间</label><input name="time" type="time" value="${new Date(task.plannedAt).toTimeString().slice(0,5)}" required>`});if(!values)return;await repo.put('taskInstances',{...task,plannedAt:new Date(`${task.date}T${values.time}:00`).toISOString(),status:'adjusted',updatedAt:new Date().toISOString()});await refresh();toast('事项时间已调整')});
  document.querySelectorAll('[data-action="skip-task"]').forEach(button=>button.onclick=async()=>{for(const task of skipTask(store.tasks,button.dataset.id))await repo.put('taskInstances',task);await refresh();toast('已跳过当前事项')});
  document.querySelector('[data-action="generate-menu"]')?.addEventListener('click',async()=>{try{const prefs=await repo.get('foodPreferences',store.activeBabyId)||{};const week=generateWeek(recipes,{babyId:store.activeBabyId,stage:store.activeBaby.stage,startDate:localDateKey(),mealCount:2,excluded:prefs.excluded||[],favorites:prefs.favorites||[],disliked:prefs.disliked||[],createId});await repo.put('weeklyMenus',week);await refresh();toast('本周菜单已生成')}catch(error){toast(error.message)}});
  document.querySelectorAll('[data-action="replace-meal"]').forEach(button=>button.onclick=async()=>{const prefs=await repo.get('foodPreferences',store.activeBabyId)||{};const week=replaceMeal(store.week,button.dataset.id,recipes,{stage:store.activeBaby.stage,excluded:prefs.excluded||[],favorites:prefs.favorites||[],disliked:prefs.disliked||[]});await repo.put('weeklyMenus',week);await refresh();toast('已更换为安全候选食谱')});
  document.querySelectorAll('[data-action="meal-status"]').forEach(button=>button.onclick=async()=>{await repo.put('weeklyMenus',setMealStatus(store.week,button.dataset.id,button.dataset.status));await refresh();toast('餐次状态已更新')});
  document.querySelector('[data-action="build-shopping"]')?.addEventListener('click',async()=>{if(!store.week)return toast('请先生成菜单');for(const item of await repo.list('shoppingItems',{babyId:store.activeBabyId}))if(!item.custom)await repo.delete('shoppingItems',item.id);for(const item of buildShoppingList(store.week,recipes,createId))await repo.put('shoppingItems',item);await refresh();toast('买菜清单已生成')});
  document.querySelectorAll('[data-action="toggle-shopping"]').forEach(input=>input.onchange=async()=>{const item=await repo.get('shoppingItems',input.dataset.id);await repo.put('shoppingItems',{...item,done:input.checked,inStock:input.checked?false:item.inStock,updatedAt:new Date().toISOString()});await refresh()});
  document.querySelectorAll('[data-action="stock-shopping"]').forEach(button=>button.onclick=async()=>{const item=await repo.get('shoppingItems',button.dataset.id);await repo.put('shoppingItems',{...item,inStock:!item.inStock,done:false,updatedAt:new Date().toISOString()});await refresh()});
  document.querySelector('[data-action="add-shopping"]')?.addEventListener('click',async()=>{const values=await openDialog({title:'添加买菜项目',body:'<label>名称</label><input name="name" required><label>数量</label><input name="quantity" type="number" min="1" value="1">'});if(values){const now=new Date().toISOString();await repo.put('shoppingItems',{id:createId(),babyId:store.activeBabyId,name:values.name.trim(),quantity:Number(values.quantity)||1,done:false,inStock:false,custom:true,createdAt:now,updatedAt:now});await refresh()}});
  document.querySelectorAll('[data-action="favorite-recipe"]').forEach(button=>button.onclick=async()=>{const prefs=await repo.get('foodPreferences',store.activeBabyId)||{id:store.activeBabyId,babyId:store.activeBabyId,excluded:[],disliked:[],favorites:[]},id=Number(button.dataset.id),set=new Set(prefs.favorites||[]);set.has(id)?set.delete(id):set.add(id);await repo.put('foodPreferences',{...prefs,favorites:[...set],updatedAt:new Date().toISOString()});await refresh()});
  document.querySelectorAll('[data-action="dislike-food"]').forEach(button=>button.onclick=async()=>{const prefs=await repo.get('foodPreferences',store.activeBabyId)||{id:store.activeBabyId,babyId:store.activeBabyId,excluded:[],disliked:[],favorites:[]},food=button.dataset.food,set=new Set(prefs.disliked||[]);set.has(food)?set.delete(food):set.add(food);await repo.put('foodPreferences',{...prefs,disliked:[...set],updatedAt:new Date().toISOString()});await refresh()});
  const filterRecipes=()=>{const query=document.getElementById('recipe-search')?.value.trim().toLowerCase()||'',stage=document.getElementById('recipe-stage')?.value||store.activeBaby.stage;document.querySelectorAll('#recipe-list .recipe-card').forEach(card=>{const text=card.textContent.toLowerCase();card.hidden=Boolean(query&&!text.includes(query))||Boolean(stage!=='all'&&card.dataset.stage!==stage)})};
  document.getElementById('recipe-search')?.addEventListener('input',filterRecipes);document.getElementById('recipe-stage')?.addEventListener('change',filterRecipes);
  document.querySelectorAll('[data-quick],[data-record]').forEach(button=>button.onclick=()=>openRecord(button.dataset.quick||button.dataset.record));
  document.querySelector('[data-action="sleep-start"]')?.addEventListener('click',async()=>{await repo.put('sleepSessions',createSleepSession({babyId:store.activeBabyId,type:'nap',startAt:new Date().toISOString()},createId));await refresh();toast('睡眠计时已开始')});
  document.querySelector('[data-action="sleep-end"]')?.addEventListener('click',async event=>{const item=await repo.get('sleepSessions',event.currentTarget.dataset.id),endAt=new Date().toISOString();await repo.put('sleepSessions',{...item,endAt,durationMinutes:Math.round((new Date(endAt)-new Date(item.startAt))/60000),updatedAt:endAt});await refresh();toast('睡眠记录已完成')});
  document.querySelectorAll('[data-action="edit-record"]').forEach(button=>button.onclick=async()=>{const item=await repo.get('dailyRecords',button.dataset.id),values=await openDialog({title:'编辑记录',body:`<label>数值</label><input name="value" type="number" min="0" value="${esc(item.value)}" required><label>备注</label><textarea name="note">${esc(item.note||'')}</textarea>`});if(!values)return;await repo.put('dailyRecords',{...item,value:Number(values.value),note:values.note.trim(),updatedAt:new Date().toISOString()});await refresh();toast('记录已更新')});
  document.querySelectorAll('[data-action="delete-record"]').forEach(button=>button.onclick=async()=>{if(!confirm('删除这条记录？'))return;await repo.delete('dailyRecords',button.dataset.id);await refresh();toast('记录已删除')});
  document.querySelectorAll('[data-action="edit-sleep"]').forEach(button=>button.onclick=async()=>{const item=await repo.get('sleepSessions',button.dataset.id),values=await openDialog({title:'编辑睡眠',body:`<label>睡眠分钟</label><input name="minutes" type="number" min="1" value="${esc(item.durationMinutes)}" required><label>备注</label><textarea name="note">${esc(item.note||'')}</textarea>`});if(!values)return;const durationMinutes=Number(values.minutes),endAt=new Date(new Date(item.startAt).getTime()+durationMinutes*60000).toISOString();await repo.put('sleepSessions',{...item,endAt,durationMinutes,note:values.note.trim(),updatedAt:new Date().toISOString()});await refresh();toast('睡眠记录已更新')});
  document.querySelectorAll('[data-action="delete-sleep"]').forEach(button=>button.onclick=async()=>{if(!confirm('删除这条睡眠记录？'))return;await repo.delete('sleepSessions',button.dataset.id);await refresh();toast('睡眠记录已删除')});
  document.querySelectorAll('[data-action="add-reaction"]').forEach(button=>button.onclick=async()=>{const item=await repo.get('newFoodObservations',button.dataset.id),values=await openDialog({title:`记录 ${esc(item.name)} 的反应`,body:`<label>日期</label><input name="date" type="date" value="${localDateKey()}" required><label>反应</label><textarea name="reaction" required></textarea>`});if(!values)return;await repo.put('newFoodObservations',{...item,reactions:[...(item.reactions||[]),{date:values.date,text:values.reaction.trim()}],updatedAt:new Date().toISOString()});await refresh();toast('观察反应已保存')});
  document.querySelectorAll('[data-action="delete-observation"]').forEach(button=>button.onclick=async()=>{if(!confirm('删除这项新食物观察？'))return;await repo.delete('newFoodObservations',button.dataset.id);await refresh()});
  document.querySelectorAll('[data-action="complete-reminder"]').forEach(button=>button.onclick=async()=>{const item=await repo.get('reminders',button.dataset.id),now=new Date().toISOString();await repo.put('reminders',{...item,completedAt:now,updatedAt:now});await refresh();toast('提醒已完成')});
  document.querySelectorAll('[data-action="delete-reminder"]').forEach(button=>button.onclick=async()=>{if(!confirm('删除这条提醒？'))return;await repo.delete('reminders',button.dataset.id);await refresh()});
  document.querySelectorAll('[data-growth]').forEach(button=>button.onclick=()=>openGrowth(button.dataset.growth));
  document.getElementById('chart-type')?.addEventListener('change',async event=>{const records=await repo.list('growthMeasurements',{babyId:store.activeBabyId});document.getElementById('growth-chart').innerHTML=chartSvg(chartModel(records,event.target.value))});
  document.getElementById('timeline-filter')?.addEventListener('change',event=>{document.querySelectorAll('#view-growth .timeline article').forEach(item=>item.hidden=event.target.value!=='all'&&item.dataset.type!==event.target.value)});
  document.getElementById('active-baby')?.addEventListener('change',async event=>{await store.setActiveBaby(event.target.value);await ensureDailySchedule(repo,store.activeBaby);await refresh()});
  document.querySelector('[data-action="add-baby"]')?.addEventListener('click',()=>openBaby());
  document.querySelector('[data-action="edit-profile"]')?.addEventListener('click',()=>openProfile());
  document.querySelector('[data-action="delete-baby"]')?.addEventListener('click',deleteBaby);
  document.querySelector('[data-action="edit-schedule"]')?.addEventListener('click',()=>openSchedule());
  document.querySelector('[data-action="food-preferences"]')?.addEventListener('click',()=>openPreferences());
  document.querySelector('[data-action="notification-settings"]')?.addEventListener('click',enableNotifications);
  document.querySelector('[data-action="export-data"]')?.addEventListener('click',exportData);
  document.getElementById('backup-file')?.addEventListener('change',importData);
  document.querySelector('[data-action="reset-data"]')?.addEventListener('click',resetData);
 }
 async function openRecord(type){if(type==='new-food'){const values=await openDialog({title:'记录新食材',body:`<label>食材名称</label><input name="name" required><label>首次尝试日期</label><input name="date" type="date" value="${localDateKey()}" required><label>观察备注</label><textarea name="note"></textarea>`});if(values){const item=createObservation({babyId:store.activeBabyId,name:values.name,date:values.date},createId);await repo.put('newFoodObservations',{...item,note:values.note});await refresh();toast('已开始三天观察')}return}if(type==='reminder'){const values=await openDialog({title:'添加提醒',body:`<label>类型</label><select name="type"><option value="vaccine">疫苗</option><option value="checkup">体检</option><option value="custom">自定义</option></select><label>标题</label><input name="title" required><label>日期</label><input name="dueDate" type="date" value="${localDateKey()}" required>`});if(values){const now=new Date().toISOString();await repo.put('reminders',{id:createId(),babyId:store.activeBabyId,...values,completedAt:null,createdAt:now,updatedAt:now});await refresh();toast('提醒已保存')}return}const label=type==='milk'?'奶量':type==='water'?'喝水':type==='sleep'?'睡眠分钟':'排便次数';const values=await openDialog({title:`记录${label}`,body:`<label for="record-value">${label}</label><input id="record-value" name="value" type="number" min="0" required><label for="record-note">备注</label><textarea id="record-note" name="note"></textarea>`});if(!values)return;if(type==='sleep'){const end=new Date(),start=new Date(end.getTime()-Number(values.value)*60000);await repo.put('sleepSessions',createSleepSession({babyId:store.activeBabyId,startAt:start.toISOString(),endAt:end.toISOString(),note:values.note},createId))}else await repo.put('dailyRecords',createNumericRecord({babyId:store.activeBabyId,type,value:values.value,note:values.note,occurredAt:new Date().toISOString()},createId));await refresh();toast('记录已保存')}
 async function openGrowth(field){if(field==='tooth'){const values=await openDialog({title:'记录长牙',body:`<label>第几颗牙</label><input name="number" type="number" min="1" required><label>日期</label><input name="date" type="date" value="${localDateKey()}" required><label>备注</label><textarea name="note"></textarea>`});if(values){const now=new Date().toISOString();await repo.put('toothRecords',{id:createId(),babyId:store.activeBabyId,number:Number(values.number),date:values.date,note:values.note.trim(),createdAt:now,updatedAt:now});await refresh();toast('长牙记录已保存')}return}const values=await openDialog({title:`记录${field==='weight'?'体重':'身高'}`,body:`<label for="growth-value">数值</label><input id="growth-value" name="value" type="number" step="0.1" min="0" required><label for="growth-date">日期</label><input id="growth-date" name="date" type="date" value="${localDateKey()}" required>`});if(!values)return;const now=new Date().toISOString();await repo.put('growthMeasurements',{id:createId(),babyId:store.activeBabyId,date:values.date,[field]:Number(values.value),createdAt:now,updatedAt:now});await refresh();toast('成长记录已保存')}
 async function openBaby(){const values=await openDialog({title:'添加宝宝',body:'<label>昵称</label><input name="name" required><label>出生日期</label><input name="birthday" type="date"><label>辅食阶段</label><select name="stage"><option value="stage1">初尝泥糊期</option><option value="stage2">稠泥碎末期</option><option value="stage3">软烂颗粒期</option><option value="stage4">咀嚼练习期</option><option value="stage5">家庭餐过渡期</option></select>'});if(values)await saveOnboarding(values)}
 async function openProfile(){const baby=store.activeBaby,values=await openDialog({title:'编辑宝宝资料',body:`<label>昵称</label><input name="name" value="${esc(baby.name)}" required><label>生日</label><input name="birthday" type="date" value="${esc(baby.birthday||'')}"><label>辅食阶段</label><select name="stage"><option value="${esc(baby.stage)}">保持当前阶段</option><option value="stage1">初尝泥糊期</option><option value="stage2">稠泥碎末期</option><option value="stage3">软烂颗粒期</option><option value="stage4">咀嚼练习期</option><option value="stage5">家庭餐过渡期</option></select>`});if(values){await repo.put('babies',{...baby,...values,updatedAt:new Date().toISOString()});await refresh()}}
 async function deleteBaby(){if(store.babies.length<=1)return toast('至少保留一个宝宝');if(!confirm(`删除“${store.activeBaby.name}”及其全部本地数据？`))return;const id=store.activeBabyId;for(const name of STORE_NAMES){for(const item of await repo.list(name,{babyId:id}))await repo.delete(name,item.id)}await repo.delete('babies',id);const next=store.babies.find(b=>b.id!==id);await repo.put('appSettings',{id:'global',activeBabyId:next.id,updatedAt:new Date().toISOString()});await refresh();toast('宝宝及其本地数据已删除')}
 async function openSchedule(){const template=(await repo.list('scheduleTemplates',{babyId:store.activeBabyId}))[0]||createDefaultTemplate(store.activeBabyId),fields=template.rules.map((rule,index)=>`<fieldset><label><input name="enabled-${index}" type="checkbox" ${index===0||rule.enabled!==false?'checked':''} ${index===0?'disabled':''}>启用</label><label>事项名称</label><input name="title-${index}" value="${esc(rule.title)}" required><label>距上一事项（分钟）</label><input name="after-${index}" type="number" min="0" value="${rule.afterMinutes}" required></fieldset>`).join(''),values=await openDialog({title:'配置每日作息',body:`${fields}<fieldset><legend>添加自定义事项（可选）</legend><label>名称</label><input name="customTitle"><label>类型</label><select name="customType"><option value="meal">辅食</option><option value="milk">喝奶</option><option value="sleep">睡眠</option><option value="custom">其他</option></select><label>距上一事项（分钟）</label><input name="customAfter" type="number" min="0" value="60"></fieldset>`});if(values){template.rules=template.rules.map((rule,index)=>({...rule,title:values[`title-${index}`].trim(),afterMinutes:Number(values[`after-${index}`]),enabled:index===0||values[`enabled-${index}`]==='on'})).filter(rule=>rule.enabled!==false);if(values.customTitle?.trim())template.rules.push({type:values.customType,title:values.customTitle.trim(),afterMinutes:Number(values.customAfter)});template.updatedAt=new Date().toISOString();await repo.put('scheduleTemplates',template);toast('作息模板已保存，明日任务将使用新安排')}}
 async function openPreferences(){const prefs=await repo.get('foodPreferences',store.activeBabyId)||{id:store.activeBabyId,babyId:store.activeBabyId,excluded:[],disliked:[],favorites:[]},values=await openDialog({title:'饮食偏好',body:`<label>绝对排除（逗号分隔）</label><input name="excluded" value="${esc((prefs.excluded||[]).join(','))}"><label>不喜欢（逗号分隔）</label><input name="disliked" value="${esc((prefs.disliked||[]).join(','))}">`});if(values){const split=value=>value.split(/[,，]/).map(x=>x.trim()).filter(Boolean),now=new Date().toISOString();await repo.put('foodPreferences',{...prefs,excluded:split(values.excluded),disliked:split(values.disliked),createdAt:prefs.createdAt||now,updatedAt:now});await refresh();toast('饮食规则已保存')}}
 async function enableNotifications(){if(notificationState()==='unsupported')return toast('当前浏览器不支持通知');const settings=await repo.get('appSettings','global')||{id:'global'};if(settings.notificationsEnabled!==false&&notificationState()==='granted'){await repo.put('appSettings',{...settings,notificationsEnabled:false,updatedAt:new Date().toISOString()});clearTimeout(notificationTimer);return toast('应用内提醒已关闭')}if(!confirm('通知只能尽力提醒，不能作为医疗或安全报警。是否继续开启？'))return;const permission=await requestNotifications();if(permission==='granted'){await repo.put('appSettings',{...settings,notificationsEnabled:true,updatedAt:new Date().toISOString()});await scheduleNotifications()}toast(permission==='granted'?'通知已开启，再次点击可关闭':'未获得通知权限')}
 async function exportData(){const backup=await createBackup(repo),blob=new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`宝宝成长助手V1备份-${localDateKey()}.json`;link.click();URL.revokeObjectURL(link.href);localStorage.setItem('babyGrowthAssistantV1LastExport',backup.exportedAt);toast('备份已导出')}
 async function importData(event){const file=event.target.files[0];if(!file)return;try{const text=await file.text(),preview=previewBackup(text);if(confirm(`备份包含 ${preview.babyCount} 个宝宝、${preview.recordCount} 条数据。确认覆盖当前数据？`)){await importBackup(repo,text);await refresh();toast('备份导入成功')}}catch(error){toast(error.message)}finally{event.target.value=''}}
 async function resetData(){if(!confirm('确定清除这台设备上的全部 V1 数据吗？此操作不可恢复。'))return;if(!confirm('请再次确认：是否已导出备份并继续清除？'))return;await resetApplication(repo);location.reload()}
 if(model.needsOnboarding){document.body.insertAdjacentHTML('beforeend',onboardingView());document.getElementById('onboarding-form').onsubmit=event=>{event.preventDefault();saveOnboarding(Object.fromEntries(new FormData(event.currentTarget)))}}else{await render();if('serviceWorker'in navigator){notificationRegistration=await navigator.serviceWorker.register('./service-worker.js');wireUpdatePrompt(notificationRegistration);await scheduleNotifications()}document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refresh()});window.addEventListener('focus',scheduleNotifications)}
}

if(typeof document!=='undefined')browserApp().catch(error=>{console.error(error);document.body.innerHTML=`<main class="fatal"><h1>应用启动失败</h1><p>${String(error.message||error)}</p><button onclick="location.reload()">重新加载</button></main>`});
